language: go 

go:
- "1.14"

env:
- GO111MODULE=on

# before_install:

script:
  - make

# after_success:

notifications:
  email:
    recipients:
        - bin646891055@gmail.com
    on_success: change
    on_failure: always