
workspace = "."
file = "./config.toml"
mode = "all"

[GRPCConfig]
HttpPort = "9500"
CertPath = "test/tls/server.crt"
KeyPath  = "test/tls/server.key"
Host     = "server.grpc.io"         # for test
[WebConfig]
HttpPort   = "80"
HttpsPort  = "443"
StaticPath = "./"
CertPath   = "test/tls/server.crt"
KeyPath    = "test/tls/server.key"
Host       = "server.grpc.io"         # for test
[WebConfig.ReverseProxy]
"prometheus" = "http://127.0.0.1:9000"
#"grafana"   = "http://127.0.0.1:3000"

[LogConfig]
Level = "debug"

[RedisConfig]
Network      = "tcp"
Addr         = "127.0.0.1:6379"
Password     = "password"
DB           = 0
PoolSize     = 10
MinIdleConns = 3

[MysqlConfig]
MaxIdleConns = 33
MaxOpenConns = 100
[[MysqlConfig.Conns]]
User 	 = "root"
Password = "password"
Host	 = "127.0.0.1"
Port	 = "3306"
DB		 = "testdb"
# [[MysqlConfig.Conns]]
# User 	   = "user1"
# Password = "password"
# Host	   = "127.0.0.1"
# Port	   = "3306"
# DB       = "db"
