
workspace = "."
file = "./config.toml"

[GRPCConfig]
HttpPort = "80"
CertPath = "tls/server.crt"
KeyPath  = "tls/server.key"
Host     = "binacs.cn"
[WebConfig]
HttpPort = "80"

[LogConfig]
Level = "debug"

[RedisConfig]
Network      = "tcp"
Addr         = "127.0.0.1:6379"
Password     = "password"
DB           = 0
PoolSize     = 10
MinIdleConns = 3

[MysqlConfig]
MaxIdleConns = 33
MaxOpenConns = 100
[[MysqlConfig.Conns]]
User 	 = "user1"
Password = "password"
Host	 = "127.0.0.1"
Port	 = "3306"
DB		 = "db"
[[MysqlConfig.Conns]]
User 	 = "user1"
Password = "password"
Host	 = "127.0.0.1"
Port	 = "3306"
DB		 = "db"
