workspace = "/work/"
file = "/work/kubernetes/config.toml"
mode = "all"

[GRPCConfig]
HttpPort = "9500"
CertPath = "test/tls/api_server.crt"
KeyPath  = "test/tls/api_server.key"
Host     = "server.grpc.io"           # for test
[WebConfig]
HttpPort   = "80"
HttpsPort  = "443"
StaticPath = "/work/static/"
TmplPath   = "./test/template/"
CertPath   = "/work/tls/server.crt"
KeyPath    = "/work/tls/server.key"
Host       = "server.grpc.io"         # for test
[WebConfig.K8sService]
"CryptoBASE64" = "cryptfunc-base64-svc.cryptfunc"
"CryptoAES"    = "cryptfunc-aes-svc.cryptfunc"
"CryptoDES"    = "cryptfunc-des-svc.cryptfunc"

[LogConfig]
File  = "/work/server.log"
Level = "debug"

[TraceConfig]
"ServiceName"   = "binacs-cn"
"AgentHostPort" = "127.0.0.1:6831"

[RedisConfig]
Network      = "tcp"
Addr         = "redis.namepace:6379"
Password     = "password"
DB           = 0
PoolSize     = 10
MinIdleConns = 3

[MysqlConfig]
MaxIdleConns = 33
MaxOpenConns = 100
[[MysqlConfig.Conns]]
User     = "root"
Password = "password"
Host     = "mysql.namepace"
Port     = "3306"
DB       = "testdb"
